name: HTML Preview
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HTML Preview Check
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'index.html' # Change this if your HTML file is named differently
          job_summary: true
